name: bidgame
description: "Fun App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.3
  cloud_functions: ^5.0.4
  firebase_storage: ^12.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6
  firebase_app_check: ^0.3.0+4
  url_launcher: ^6.1.7
  permission_handler: ^12.0.0+1
  path_provider: ^2.0.11
  file_picker: ^10.1.9
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.1.0
  firebase_messaging: ^15.0.4
  mailer: ^6.1.2
  twilio_flutter: ^0.9.0
  onesignal_flutter: ^5.2.4
  flutter_contacts: ^1.1.9+2
  google_fonts: ^4.0.3
  window_manager: ^0.3.3
  pwa_install: ^0.0.5
  cached_network_image: ^3.3.0





  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  mockito: ^5.0.16
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1


flutter_icons:
    android: true
    ios: true
    min_sdk_android: 21 # optional


flutter_native_splash:
  color: "#E2E5EA"
  image: "assets/etqan.png"
  color_dark: "#010101"
  image_dark: "assets/etqan.png"
  duration: 3000
  android_gravity: center
  ios_content_mode: center


flutter:
  uses-material-design: true



